### ISSUE TITLE
Many converted tests have "::" in the request url

### ISSUE THREAD

**Issue by chyde80** [apideck-libraries/postman-to-k6#101]
This produces: `GoError: group and check names may not contain '::'`

snippet of a generated test that is causing the issue:
``` postman[Symbol.for("define")]({
  name: "Returns a list of Entity Types.",
  id: "3e5bf7c1-c6c2-4b7a-b08f-7027a55dd05a",
  method: "GET",
  address: "{{baseUrl}}/entities/types?q=lic",
  headers: {
    Accept: "application/json"
  },
  post(response) {
    // Validate status 2xx
    pm.test("[GET]::/entities/types - Status code is 2xx", function() {
      pm.response.to.be.success;
    });```

**Comment by thim81** [comment]
hi @chyde80 ,

Are you using Portman to generate the Postman collection?

If you do, I have added the following to the `globals` in the Portman config

```
{
  "version": 1.0,
  "globals": {
    "stripResponseExamples": true,
    "portmanReplacements": [
      {
        "searchFor": "::",
        "replaceWith": "=="
      }
    ]
  }
}
```
This will replace all the `::` with `==` before being exported as a Postman collection, which is used to be converted into the K6 scripts.

**Comment by chyde80** [comment]
I am. I will try that. Thank you!!
