### ISSUE TITLE
Is pm.request.body.raw support ?

### ISSUE THREAD

**Issue by titanzx** [apideck-libraries/postman-to-k6#136]
Is pm.request.body.raw support ?

**Comment by thim81** [comment]
We will have to verify it.

You could give it a go and see if it returns the body?

**Comment by titanzx** [comment]
This
<img width="919" alt="image" src="https://github.com/user-attachments/assets/f3c1db7d-04ef-4f16-8754-17468dc68cea">

**Comment by thim81** [comment]
hi @titanzx 

We just released version 1.13.0 which contains support for pm.request: headers, url, method, name, id, body, body.raw.

Thanks for opening the request. Let us know if you are missing other features.
