### ISSUE TITLE
The moduleSpecifier "../../libs/shim/urijs.js" couldn't be found on local disk.

### ISSUE THREAD

**Issue by CMathgician** [apideck-libraries/postman-to-k6#49]
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/6632239/158386309-beceabe9-cdc0-4dd7-acfd-39e115f88779.png">

Similar to this issue before: https://github.com/grafana/postman-to-k6/issues/78
I changed the `import "../../libs/shim/urijs.js";` on requests into `import "../libs/shim/urijs.js";`
and it runs well

**Comment by thim81** [comment]
I think I see the issue.

Can you confirm or share if the requests in Postman or in a folder?
If they are not could, you try to put them in a folder and see if that solves the issue?

I use the "seperate" parameters but I think it is linked to requests not being in a folder, which results in an incorrect "import" path.

**Comment by CMathgician** [comment]
After I add a folder in postman and put the request there, and execute the same command. The structure changes like this `Request/OTP`
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/6632239/158415463-7aa0f7bc-37f6-4176-a38c-8e7c41eec678.png">

**Comment by thim81** [comment]
@CMathgician 

Thanks for providing the info to reproduce the issue.
I'm going to reopen the issue and will try to fix it when I have some free time at hands.

The bug is linked to requests not being in folders, while the convertor was expecting it in a folder.

**Comment by thim81** [comment]
@CMathgician The relative path issue is resolved and it will be part of the upcoming postman-to-k6 release.

Thanks for taking the time to report the issue.

**Comment by CMathgician** [comment]
Thank you @thim81

**Comment by thim81** [comment]
hi @CMathgician, The latest postman-to-k6 version (1.8.5) contains this enhancement.
