### ISSUE TITLE
Qustion - How to convert multiple postman collections at once..?

### ISSUE THREAD

**Issue by EdisonEy** [apideck-libraries/postman-to-k6#92]
is it possible to convert 2 postman collections at once..?

for eg: is it possible to do something like ` postman-to-k6 collection1.json  collection2.json -o k6-script.js` like this..?

if not is there any workaround to achieve the same..?

**Comment by thim81** [comment]
hi @EdisonEy 

That is not possible through the postman-to-k6 CLI, but some libraries could do this before you pass it to the CLI.
Like: https://www.npmjs.com/package/postman-combine-collections (disclaimer, I have not tested the library)
